# Generated by Django 3.2.9 on 2022-06-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
